Try to use libvirt

diff --git a/build/ci/install-olm-manual b/build/ci/install-olm-manual
--- a/build/ci/install-olm-manual
+++ b/build/ci/install-olm-manual
@@ -11,21 +11,24 @@ kubectl apply -f https://github.com/operator-framework/operator-lifecycle-manage
 kubectl rollout status -w deployment/olm-operator --namespace=olm
 kubectl rollout status -w deployment/catalog-operator --namespace=olm
 
-retries=100
-until [[ $retries == 0 || $new_csv_phase == "Succeeded" ]]; do
-    new_csv_phase=$(kubectl get csv -n olm packageserver -o jsonpath='{.status.phase}' 2>/dev/null || echo "Waiting for CSV to appear")
-    if [[ $new_csv_phase != "$csv_phase" ]]; then
-        csv_phase=$new_csv_phase
-        echo "Package server phase: $csv_phase"
-    fi
-    sleep 1
-    retries=$((retries - 1))
-done
+sleep 60
 
-if [ $retries == 0 ]; then
-    echo "CSV \"packageserver\" failed to reach phase succeeded"
-    exit 1
-fi
+
+#retries=100
+#until [[ $retries == 0 || $new_csv_phase == "Succeeded" ]]; do
+#    new_csv_phase=$(kubectl get csv -n olm packageserver -o jsonpath='{.status.phase}' 2>/dev/null || echo "Waiting for CSV to appear")
+#    if [[ $new_csv_phase != "$csv_phase" ]]; then
+#        csv_phase=$new_csv_phase
+#        echo "Package server phase: $csv_phase"
+#    fi
+#    sleep 1
+#    retries=$((retries - 1))
+#done
+
+#if [ $retries == 0 ]; then
+#    echo "CSV \"packageserver\" failed to reach phase succeeded"
+#    exit 1
+#fi
 
 kubectl rollout status -w deployment/packageserver --namespace=olm
 
